# Generated by Django 4.1.7 on 2023-04-14 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_rename_doctoratmedicapractice_doctoratmedicalpractice"),
        ("triage", "0002_disease_diseasehassymptom_encounter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounterfollowup",
            name="medical_practice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.medicalpractice",
            ),
        ),
    ]
