# Generated by Django 4.1.7 on 2023-04-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0003_encounterfollowup_medical_practice"),
    ]

    operations = [
        migrations.AddField(
            model_name="disease",
            name="cui",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="disease",
            name="icd10",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="disease",
            name="icpc2p",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="disease",
            name="snomed_ct",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
