# Generated by Django 4.1.7 on 2023-04-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0004_disease_cui_disease_icd10_disease_icpc2p_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="encounter",
            name="description",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
