# Generated by Django 4.1.7 on 2023-04-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0005_alter_encounter_age_alter_encounter_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
    ]
