# Generated by Django 4.1.7 on 2023-05-06 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0007_alter_encounter_urgency_prediction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("citizen_service_number", models.CharField(max_length=15)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=6
                    ),
                ),
                ("date_of_birth", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="DiseaseHasSymptom",
        ),
        migrations.DeleteModel(
            name="Symptom",
        ),
        migrations.AddField(
            model_name="encounter",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="triage.patient",
            ),
        ),
    ]
