# Generated by Django 4.1.7 on 2023-05-06 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0005_rename_medical_center_id_medicalpractice_medical_practice_id",
        ),
        ("triage", "0008_patient_delete_diseasehassymptom_delete_symptom_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "timestamp_registered",
                    models.DateTimeField(auto_created=True, auto_now=True),
                ),
                (
                    "consultation_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="triage.encounter",
                    ),
                ),
                (
                    "medical_practice",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.medicalpractice",
                    ),
                ),
            ],
            options={
                "db_table": "Consultation",
                "managed": True,
            },
        ),
        migrations.RemoveField(
            model_name="encounterfollowup",
            name="encounter",
        ),
        migrations.RemoveField(
            model_name="encounterfollowup",
            name="medical_practice",
        ),
        migrations.DeleteModel(
            name="MedicalCenter",
        ),
        migrations.AlterModelOptions(
            name="encounterdiseaseprediction",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="disease",
            table="Disease",
        ),
        migrations.AlterModelTable(
            name="encounterdiseaseprediction",
            table="EncounterDiseasePrediction",
        ),
        migrations.DeleteModel(
            name="EncounterFollowUp",
        ),
    ]
