# Generated by Django 4.1.7 on 2023-05-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0009_consultation_remove_encounterfollowup_encounter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
