# Generated by Django 4.1.7 on 2023-05-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0010_alter_patient_date_of_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAIModelConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_active_since",
                    models.DateTimeField(auto_created=True, null=True),
                ),
                ("datetime_created", models.DateTimeField(auto_created=True)),
                ("active", models.BooleanField(default=False)),
                ("model", models.CharField(max_length=50)),
                ("temperature", models.FloatField(default=0.0, max_length=3)),
                ("maximum_length", models.IntegerField(default=256)),
                ("top_p", models.FloatField(default=1.0, max_length=3)),
                ("frequency_penalty", models.FloatField(default=0.0, max_length=3)),
                ("presence_penalty", models.FloatField(default=0.0, max_length=3)),
                ("system_description", models.TextField()),
            ],
        ),
    ]
