# Generated by Django 4.1.7 on 2023-05-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0011_openaimodelconfiguration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openaimodelconfiguration",
            name="datetime_active_since",
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
