# Generated by Django 4.1.7 on 2023-05-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0012_alter_openaimodelconfiguration_datetime_active_since"),
    ]

    operations = [
        migrations.AddField(
            model_name="openaimodelconfiguration",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("triage", "Triage"),
                    ("differential_diagnosis", "Differential diagnosis"),
                    ("additional_questions", "Additional questions"),
                    ("other", "Other"),
                ],
                default="differential_diagnosis",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
