# Generated by Django 4.1.7 on 2023-05-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0013_openaimodelconfiguration_model_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="openaimodelconfiguration",
            old_name="maximum_length",
            new_name="max_tokens",
        ),
        migrations.AlterField(
            model_name="openaimodelconfiguration",
            name="system_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
