# Generated by Django 4.1.7 on 2023-05-10 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0005_rename_medical_center_id_medicalpractice_medical_practice_id",
        ),
        ("triage", "0016_consultation_actual_disease_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.doctor",
            ),
        ),
    ]
