# Generated by Django 4.1.7 on 2023-04-29 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_rename_doctoratmedicapractice_doctoratmedicalpractice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctoratmedicalpractice",
            old_name="medical_center",
            new_name="medical_practice",
        ),
        migrations.AlterUniqueTogether(
            name="doctoratmedicalpractice",
            unique_together={("doctor", "medical_practice")},
        ),
    ]
