# Generated by Django 4.1.7 on 2023-05-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0004_rename_medical_center_doctoratmedicalpractice_medical_practice_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicalpractice",
            old_name="medical_center_id",
            new_name="medical_practice_id",
        ),
    ]
